# Generated by Django 4.1.1 on 2022-10-16 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soal', '0002_bank_soal_delete_mahasiswa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materi', models.CharField(max_length=80)),
                ('soal', models.TextField(max_length=200)),
                ('kunci_jawaban', models.TextField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Bank_Soal',
        ),
    ]
