# Generated by Django 4.1.1 on 2022-10-16 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soal', '0003_soal_delete_bank_soal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nama_Materi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_materi', models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='soal',
            name='nama_materi_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='soal.nama_materi'),
        ),
    ]
